// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8K-V-HWH-sa-DBnaVkEm6j6HhBescbM',
    appId: '1:657821912297:web:1e4924b6739155858ff478',
    messagingSenderId: '657821912297',
    projectId: 'lmsapp-5730b',
    authDomain: 'lmsapp-5730b.firebaseapp.com',
    storageBucket: 'lmsapp-5730b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChje8P0J7l9k0ERBTsbgZ9NfPRjA8qssE',
    appId: '1:657821912297:android:a95e93e45b42be698ff478',
    messagingSenderId: '657821912297',
    projectId: 'lmsapp-5730b',
    storageBucket: 'lmsapp-5730b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoi0SEBY89ws-k2TQNzFUANN7Z50wbM60',
    appId: '1:657821912297:ios:1dc85cac8221469f8ff478',
    messagingSenderId: '657821912297',
    projectId: 'lmsapp-5730b',
    storageBucket: 'lmsapp-5730b.firebasestorage.app',
    iosClientId: '657821912297-r6ro36u8cjonagihb5uo1iten8pj3o0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.inteneeLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoi0SEBY89ws-k2TQNzFUANN7Z50wbM60',
    appId: '1:657821912297:ios:1dc85cac8221469f8ff478',
    messagingSenderId: '657821912297',
    projectId: 'lmsapp-5730b',
    storageBucket: 'lmsapp-5730b.firebasestorage.app',
    iosClientId: '657821912297-r6ro36u8cjonagihb5uo1iten8pj3o0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.inteneeLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ8K-V-HWH-sa-DBnaVkEm6j6HhBescbM',
    appId: '1:657821912297:web:b4a4f2f89ce7611d8ff478',
    messagingSenderId: '657821912297',
    projectId: 'lmsapp-5730b',
    authDomain: 'lmsapp-5730b.firebaseapp.com',
    storageBucket: 'lmsapp-5730b.firebasestorage.app',
  );
}
